import mongoose, { Schema } from 'mongoose';
import { IProductDocument, IProductModel } from './product.interface';

/**
 * Pricing Detail Schema
 */
const pricingDetailSchema = new Schema({
    price: {
        type: Number,
        required: true,
        min: 0,
        default: 0
    },
    setupFee: {
        type: Number,
        required: true,
        min: 0,
        default: 0
    },
    renewPrice: {
        type: Number,
        required: true,
        min: 0,
        default: 0
    },
    enable: {
        type: Boolean,
        required: true,
        default: false
    }
}, { _id: false });

/**
 * Currency Pricing Schema
 */
const currencyPricingSchema = new Schema({
    currency: {
        type: String,
        required: true,
        enum: ['BDT', 'USD', 'EUR', 'GBP']
    },
    monthly: pricingDetailSchema,
    quarterly: pricingDetailSchema,
    semiAnnually: pricingDetailSchema,
    annually: pricingDetailSchema,
    biennially: pricingDetailSchema,
    triennially: pricingDetailSchema
}, { _id: false });

/**
 * Module Configuration Schema
 */
const moduleConfigSchema = new Schema({
    name: {
        type: String,
        enum: ['cpanel', 'directadmin', 'plesk', 'virtualizor', 'none'],
        default: 'cpanel'
    },
    serverGroup: {
        type: String,
        trim: true
    },
    packageName: {
        type: String,
        trim: true
    }
}, { _id: false });

/**
 * Free Domain Settings Schema
 */
const freeDomainSchema = new Schema({
    enabled: {
        type: Boolean,
        default: false
    },
    type: {
        type: String,
        enum: ['none', 'once', 'recurring'],
        default: 'none'
    },
    paymentTerms: {
        type: [String],
        default: []
    },
    tlds: {
        type: [String],
        default: []
    }
}, { _id: false });

/**
 * Product Schema
 */
const productSchema = new Schema<IProductDocument, IProductModel>(
    {
        name: {
            type: String,
            required: [true, 'Product name is required'],
            trim: true,
            minlength: [3, 'Product name must be at least 3 characters'],
            maxlength: [100, 'Product name cannot exceed 100 characters'],
            unique: true
        },
        type: {
            type: String,
            required: [true, 'Product type is required'],
            enum: {
                values: ['hosting', 'vps', 'domain', 'ssl'],
                message: '{VALUE} is not a valid product type'
            }
        },
        group: {
            type: String,
            required: [true, 'Product group is required'],
            trim: true
        },
        description: {
            type: String,
            trim: true,
            maxlength: [500, 'Description cannot exceed 500 characters']
        },
        paymentType: {
            type: String,
            required: [true, 'Payment type is required'],
            enum: {
                values: ['free', 'one-time', 'recurring'],
                message: '{VALUE} is not a valid payment type'
            },
            default: 'recurring'
        },
        pricing: {
            type: [currencyPricingSchema],
            required: function (this: IProductDocument) {
                return this.paymentType !== 'free';
            },
            validate: {
                validator: function (this: IProductDocument, v: any) {
                    if (this.paymentType === 'free') return true;
                    return v && v.length > 0;
                },
                message: 'At least one currency pricing is required'
            }
        },
        features: {
            type: [String],
            default: [],
            validate: {
                validator: function (v: string[]) {
                    return v.length <= 50;
                },
                message: 'Cannot have more than 50 features'
            }
        },
        stock: {
            type: Number,
            min: [0, 'Stock cannot be negative'],
            default: null
        },
        module: {
            type: moduleConfigSchema,
            default: undefined
        },
        freeDomain: {
            type: freeDomainSchema,
            default: undefined
        },
        isHidden: {
            type: Boolean,
            default: false,
            index: true
        },
        pid: {
            type: Number,
            unique: true,
            required: false // Generated by pre-save validation
        }
    },
    {
        timestamps: true,
        toJSON: { virtuals: true },
        toObject: { virtuals: true }
    }
);

/**
 * Indexes for better query performance
 */
productSchema.index({ type: 1, group: 1 });
productSchema.index({ name: 'text', description: 'text' });
productSchema.index({ isHidden: 1, type: 1 });
productSchema.index({ pid: 1 }, { unique: true });

/**
 * Generate 6-digit PID before validation
 */
productSchema.pre('validate', async function (this: IProductDocument, next) {
    if (!this.pid) {
        let isUnique = false;
        let attempts = 0;

        while (!isUnique && attempts < 10) {
            // Generate random 6-digit number (100000 - 999999)
            const pid = Math.floor(100000 + Math.random() * 900000);

            // Check if exists
            const existing = await mongoose.models.Product.findOne({ pid });
            if (!existing) {
                this.pid = pid;
                isUnique = true;
            }
            attempts++;
        }

        if (!isUnique) {
            next(new Error('Failed to generate unique PID after 10 attempts'));
            return;
        }
    }
    next();
});

/**
 * Pre-save middleware for validation
 */
productSchema.pre('save', function (next) {
    // Ensure at least one billing cycle is enabled if not free
    if (this.paymentType !== 'free' && this.pricing) {
        const hasEnabledCycle = this.pricing.some(currency => {
            return ['monthly', 'quarterly', 'semiAnnually', 'annually', 'biennially', 'triennially']
                .some(cycle => (currency as any)[cycle]?.enable);
        });

        if (!hasEnabledCycle) {
            next(new Error('At least one billing cycle must be enabled'));
            return;
        }
    }
    next();
});

/**
 * Product Model
 */
const Product = mongoose.model<IProductDocument, IProductModel>('Product', productSchema);

export default Product;
